version: '3'
services:

    db:
      image: postgres
      container_name: database
      restart: always
      environment:
        POSTGRES_DB: greetings
        POSTGRES_USER: user1
        POSTGRESS_PASSWORD: use1

    python:
      build: .
      environment:
        DB_URL: postgressql://user1:use1@database:5432/apple

    web:
      image: nginx
      container_name: proxy
      restart: always
      ports: 
       - "5000:80"

